"""initial_schema

Revision ID: 10fe448cf141
Revises: 
Create Date: 2026-04-22 09:55:24.677476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10fe448cf141'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('skill_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('student','teacher','admin')", name='ck_users_role'),
    sa.CheckConstraint("skill_level IN ('beginner','intermediate','advanced')", name='ck_users_skill'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_table('chord_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chord_name', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('detected_notes', sa.JSON(), nullable=False),
    sa.Column('missing_notes', sa.JSON(), nullable=False),
    sa.Column('extra_notes', sa.JSON(), nullable=False),
    sa.Column('issue', sa.String(length=50), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chord_attempts_created', 'chord_attempts', ['created_at'], unique=False)
    op.create_index('idx_chord_attempts_user', 'chord_attempts', ['user_id'], unique=False)
    op.create_index('idx_chord_attempts_user_chord', 'chord_attempts', ['user_id', 'chord_name'], unique=False)
    op.create_table('lesson_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('song_data', sa.JSON(), nullable=False),
    sa.Column('lesson_data', sa.JSON(), nullable=False),
    sa.Column('chord_scores', sa.JSON(), nullable=False),
    sa.Column('cached_quiz', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id')
    )
    op.create_index('idx_lesson_sessions_expires', 'lesson_sessions', ['expires_at'], unique=False)
    op.create_index('idx_lesson_sessions_lesson_id', 'lesson_sessions', ['lesson_id'], unique=False)
    op.create_index('idx_lesson_sessions_user', 'lesson_sessions', ['user_id'], unique=False)
    op.create_table('quiz_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lesson_id', sa.String(length=100), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quiz_results_user', 'quiz_results', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_refresh_tokens_hash', 'refresh_tokens', ['token_hash'], unique=False)
    op.create_index('idx_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('teacher_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('chord_name', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'student_id', 'chord_name', name='uq_teacher_student_chord')
    )
    op.create_index('idx_assignments_student', 'teacher_assignments', ['student_id'], unique=False)
    op.create_index('idx_assignments_teacher', 'teacher_assignments', ['teacher_id'], unique=False)
    op.create_table('transition_drills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chord_a', sa.String(length=50), nullable=False),
    sa.Column('chord_b', sa.String(length=50), nullable=False),
    sa.Column('chord_a_symbol', sa.String(length=20), nullable=False),
    sa.Column('chord_b_symbol', sa.String(length=20), nullable=False),
    sa.Column('tpm', sa.Integer(), nullable=False),
    sa.Column('got_count', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_transition_drills_pair', 'transition_drills', ['user_id', 'chord_a', 'chord_b'], unique=False)
    op.create_index('idx_transition_drills_user', 'transition_drills', ['user_id'], unique=False)
    op.create_table('tutor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('agent_state', sa.JSON(), nullable=False),
    sa.Column('last_access', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index('idx_tutor_sessions_last', 'tutor_sessions', ['last_access'], unique=False)
    op.create_index('idx_tutor_sessions_sid', 'tutor_sessions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tutor_sessions_sid', table_name='tutor_sessions')
    op.drop_index('idx_tutor_sessions_last', table_name='tutor_sessions')
    op.drop_table('tutor_sessions')
    op.drop_index('idx_transition_drills_user', table_name='transition_drills')
    op.drop_index('idx_transition_drills_pair', table_name='transition_drills')
    op.drop_table('transition_drills')
    op.drop_index('idx_assignments_teacher', table_name='teacher_assignments')
    op.drop_index('idx_assignments_student', table_name='teacher_assignments')
    op.drop_table('teacher_assignments')
    op.drop_index('idx_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_hash', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_quiz_results_user', table_name='quiz_results')
    op.drop_table('quiz_results')
    op.drop_index('idx_lesson_sessions_user', table_name='lesson_sessions')
    op.drop_index('idx_lesson_sessions_lesson_id', table_name='lesson_sessions')
    op.drop_index('idx_lesson_sessions_expires', table_name='lesson_sessions')
    op.drop_table('lesson_sessions')
    op.drop_index('idx_chord_attempts_user_chord', table_name='chord_attempts')
    op.drop_index('idx_chord_attempts_user', table_name='chord_attempts')
    op.drop_index('idx_chord_attempts_created', table_name='chord_attempts')
    op.drop_table('chord_attempts')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
